### ISSUE TITLE
Example: Read growing log file, create a dataframe or append to existing data frame?

### ISSUE THREAD

**Issue by apiszcz** [mrocklin/streamz#103]
Is it possible to create a dataframe from a growing log file, or is pygtail a better approach?

**Comment by mrocklin** [comment]
You might want to look at  [Stream.from_textfile](http://streamz.readthedocs.io/en/latest/api.html#streamz.from_textfile)

**Comment by mrocklin** [comment]
Probably something like the following:

```python
source = Stream.from_textfile(...)
example = pd.DataFrame(...)  # provide an empty example to tell streamz about column names and dtypes
df = source.map(parse).timed_window(0.5).to_dataframe(example=example)

# do stuff with df

source.start()
```

**Comment by martindurant** [comment]
@apiszcz , were you wanting to produce a new dataframe every so often, as in the example above, or an accumulated dataframe that steadily grows with time and includes all data so far? I'm not sure how you would achieve the latter.

**Comment by mrocklin** [comment]
> or an accumulated dataframe that steadily grows with time and includes all data so far? I'm not sure how you would achieve the latter.

I think that this is an anti-pattern.  Data should always flow through streams and should not accumulate infinitely.

Instead I might ask "how did you want to convert rows into dataframes?"  The example above catches all the data for the last 500ms.  But you could imagine bundling up data by a fixed number (every 100 rows) or passing it along directly.

**Comment by martindurant** [comment]
`accumulate` with `pd.concat` would do it, I suppose, but you would surely strain the system to death as the data continues to grow. If you wish to accumulate, you ought to only keep (near) constant-size state around, as you would for a simple mean.

Probably a better example would be to buffer lines of text until some threshold, then batch-process them to parquet for later. There could be a source that watches the size of a file, without reading the text line-by-line to memory, and loads in a chunk of bytes when enough data has appeared.

**Comment by mrocklin** [comment]
> Probably a better example would be to buffer lines of text until some threshold

Yes I agree.  Things like this already exist within streamz.  You might consider `partition` or `timed_window` in `streamz.core`.  We need more operations like this on the dataframe side.  This starts to get interesting though.

**Comment by apiszcz** [comment]
I need a data frame at intervals, it will be discarded after processing.
Average size will be <10K rows, definitely less than 100K rows with 20-30
attributes so no issues processing and discarding old data. Interval range
1-20 seconds. I'm wondering if streamz or any similar capability exists to
do this. Thank you for all the thoughts on this topic.

**Comment by mrocklin** [comment]
Are the examples provided above insufficient to get you started @apiszcz ?

**Comment by apiszcz** [comment]
Will try this. ...

**Comment by apiszcz** [comment]
Those empty examples I worked that for another issue recently, someone
suggested a set of Series, is there a better way?

ndf=pd.DataFrame({'a':pd.Series([],dtype=np.uint8),
                  'b': pd.Series([], dtype=np.uint8),
                  'c': pd.Series([], dtype=np.float32),
                  'd': pd.Series([], dtype=np.uint32)})

**Comment by mrocklin** [comment]
That would be ok.  If you have some data already then you might also read a little bit of your file and pass that dataframe instead (the example doesn't have to be empty).

**Comment by apiszcz** [comment]
```
from streamz import Stream
import pandas as pd

source = Stream.filenames('test.csv')
sdf = (source.map(pd.read_csv).to_dataframe(example=...))

sdf.mean().stream.sink(print)

source = Stream.from_textfile(...)
#example = pd.DataFrame([],columns=['ab'])  # provide an empty example to tell streamz about column names and dtypes
example = pd.DataFrame({'a': pd.Series([], dtype=np.uint8),
                        'b': pd.Series([], dtype=np.uint8),
                        'c': pd.Series([], dtype=np.unint32)})


df = source.map(parse).timed_window(0.5).to_dataframe(example=example)

# do stuff with df

source.start()

```
Traceback (most recent call last):
  File "r2.py", line 7, in <module>
    sdf = (source.map(pd.read_csv).to_dataframe(example=...))
  File "lib\streamz\core.py", line 344, in to_dataframe
    return StreamingDataFrame(stream=self, example=example)
  File "lib\streamz\dataframe.py", line 267, in __init__
    return super(StreamingDataFrame, self).__init__(*args, **kwargs)
  File "lib\streamz\collection.py", line 33, in __init__
    assert isinstance(self.example, self._subtype)
AssertionError

**Comment by mrocklin** [comment]
Thanks for the error report.  I've improved the error message in https://github.com/mrocklin/streamz/pull/106

**Comment by mrocklin** [comment]
df = source.map(parse).timed_window(0.5).to_dataframe(example=example)

to_dataframe will also expect to be given a stream of dataframes.  So assuming that the output of parse is something like a python dict, we might do something like the following instead:

```python
df = (source.map(parse)
    .timed_window(0.5)  # batch into lists every 500ms 
    .filter(None)  # remove empty batches
    .map(pd.DataFrame)  # convert lists to pandas dataframes
    .to_dataframe(example=example))
```

But please understand that I'm just giving out loose examples here.  Ultimately you'll probably have to learn about these operations.  I wouldn't recommend copy-pasting what I write and expecting it to work :)

**Comment by apiszcz** [comment]
```
from streamz import Stream
import pandas as pd
import numpy as np

def parse(s):
    s.split(',')

#example = pd.DataFrame([],columns=['a','b','c'])
source = Stream.from_textfile('test.csv')
example = pd.DataFrame({'a': pd.Series([], dtype=np.uint32),
                        'b': pd.Series([], dtype=np.uint32),
                        'c': pd.Series([], dtype=np.uint32)})
df = source.map(parse).timed_window(0.5).to_dataframe(example=example)

# do stuff with df
source.start()
```
