### ISSUE TITLE
[Q] Trying to get streaming processing on json documents

### ISSUE THREAD

**Issue by timstacey** [mrocklin/streamz#178]
Hi guys, I'm trying to get up and running with streamz and running into some difficulties. My overall usecase is to:
- stream in either from a updating json document or folder of jsons
- group on metadata
- do some time windowing
- output a number per group & time-window

Also, if I had my druthers, this would all run on dask.distributed.

Granted this is a big ask and so right now I'm just trying to get a small example off the ground:

```
from streamz import Stream
from streamz.dataframe import DataFrame
import json
import pandas as pd

raw_data = json.load(open('../testing/demo_dump.json'))
data = pd.DataFrame(raw_data) # importing a raw_data store to gather the schema

source = Stream.from_textfile('./data/0.json')

df = (source.map(json.loads)
    .timed_window(0.5)  
    .filter(None) 
    .map(pd.DataFrame)
    .to_dataframe(example=data[0:0]))

source.start()
print(df)
```

Right now it's reading from a file that has 10 jsons delimited by line. When I `print(df)`, I get an empty DataFrame, but it looks like:

```
DataFrame - elements like:
Empty DataFrame
Columns: [user,x,y,z...]
```
Anyways, I'd like to pass this hurdle and get to the grouping and windowing stage. Any thoughts? Thanks so much!

**Comment by mrocklin** [comment]
Maybe you want df.stream.sink(print) instead?

**Comment by timstacey** [comment]
Thanks for the fast reply! Also tried that to no avail - when I run without `timed_window` it looks like a new error surfaces in pandas: `ValueError: If using all scalar values, you must pass an index`

Do I need to somehow pass an index with the example?

Full output:
```
If using all scalar values, you must pass an index
Traceback (most recent call last):
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/streamz/core.py", line 485, in update
    result = self.func(x, *self.args, **self.kwargs)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 330, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 461, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 6163, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 6202, in extract_index
    raise ValueError('If using all scalar values, you must pass'
ValueError: If using all scalar values, you must pass an index
tornado.application - ERROR - Future <tornado.concurrent.Future object at 0x121e2d978> exception was never retrieved: Traceback (most recent call last):
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/streamz/sources.py", line 73, in start
    yield self._emit(line)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/streamz/core.py", line 226, in _emit
    r = downstream.update(x, who=self)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/streamz/core.py", line 490, in update
    return self._emit(result)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/streamz/core.py", line 226, in _emit
    r = downstream.update(x, who=self)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/streamz/core.py", line 485, in update
    result = self.func(x, *self.args, **self.kwargs)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 330, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 461, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 6163, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/Users/tstacey/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 6202, in extract_index
    raise ValueError('If using all scalar values, you must pass'
ValueError: If using all scalar values, you must pass an index
```

**Comment by timstacey** [comment]
Seemingly fixed it - the decoder can't just be json.loads, which makes sense. Need an "open" to pair it with.

**Comment by timstacey** [comment]
For posterity, this is what worked for me:

```
from streamz import Stream
from streamz.dataframe import DataFrame
import json
import pandas as pd

def load_json(file):
    return(pd.DataFrame(json.load(open(file)),index = [0]))

source = Stream.filenames('./data/*.json') 
sdf = (source.map(load_json)
       .to_dataframe(example=data[0:0])) # where data is a preloaded dataframe with the desired schema
sdf.groupby('key1').key2.sum().stream.sink(print)
source.start()
```
