### ISSUE TITLE
Running Streamz with Dask.Distributed

### ISSUE THREAD

**Issue by seanlaw** [mrocklin/streamz#209]
I have a dask.distributed cluster setup with workers spread across multiple nodes and I am testing out a simple example to stream data to the workers to be processed:

    import dask.distributed
    import streamz

    client = dask.distributed.Client('tcp://localhost:8786')
    # client.get_metadata  # prints: <bound method Client.get_metadata of <Client: scheduler='tcp://<some ip address>:8786' processes=6 cores=96>>

    def increment(x):
        return x+1

    src = streamz.Stream()
    (src.scatter()
        .map(increment)
    )

    for x in range(10):
        src.emit(x)

However, I am receiving the following error:

    Traceback (most recent call last):
      File "./test.py", line 18, in <module>
        src.emit(x)
      File "/home/miniconda3/lib/python3.6/site-packages/streamz/core.py", line 259, in emit
        return sync(self.loop, _)
      File "/home/miniconda3/lib/python3.6/site-packages/streamz/core.py", line 1177, in sync
        if not loop._running:
    AttributeError: 'AsyncIOLoop' object has no attribute '_running'

It isn't entirely clear from the documentation what one needs to do to get around this or if this is a possible bug.

**Comment by martindurant** [comment]
If memory serves, this may be a tornado version thing - you might want to try downgrading.

**Comment by mrocklin** [comment]
If someone wants to fix this they could also just pull in the new version
of sync in distributed/utils.py into streamz/core.py  .

It should be a copy-paste drop-in solution.

**Comment by seanlaw** [comment]
Indeed, that error seems to go away when I downgrade to v4.5.3 

Although, I am using a fresh install of Miniconda and the tornado requirements are coming from dask. 

@mrocklin I'll try to take a look!

**Comment by seanlaw** [comment]
So, even with tornado=4.5, when I try to add a `gather` and `sink` like the typical example:

```
import dask.distributed
import streamz

client = dask.distributed.Client('tcp://localhost:8786')
#print(client.get_metadata)

def increment(x):
    return x+1

src = streamz.Stream()
(src.scatter().map(increment).gather().sink(print))

for x in range(10):
        src.emit(x)
```

It throws up with:

```
increment-42510a19675dd527efc7147715db657a
Traceback (most recent call last):
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 1445, in _gather
    st = self.futures[key]
KeyError: 'increment-42510a19675dd527efc7147715db657a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/home/miniconda3/lib/python3.6/site-packages/streamz/core.py", line 1195, in f
    result[0] = yield make_coro()
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/home/miniconda3/lib/python3.6/site-packages/streamz/core.py", line 254, in _
    result = yield self._emit(x)
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 828, in callback
    result_list.append(f.result())
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/home/miniconda3/lib/python3.6/site-packages/streamz/dask.py", line 97, in update
    f = yield self._emit(future)
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 828, in callback
    result_list.append(f.result())
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/home/miniconda3/lib/python3.6/site-packages/streamz/dask.py", line 122, in update
    result = yield client.gather(x, asynchronous=True)
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 1451, in _gather
    None)
  File "/app/home/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
concurrent.futures._base.CancelledError: increment-42510a19675dd527efc7147715db657a
Traceback (most recent call last):
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 1445, in _gather
    st = self.futures[key]
KeyError: 'increment-42510a19675dd527efc7147715db657a'
```

**Comment by mrocklin** [comment]
My attempts to reproduce this error locally succeeded unfortunately.

```python
import dask.distributed
import streamz
client = dask.distributed.Client()
def increment(x):
    return x+1

src = streamz.Stream()
(src.scatter().map(increment).gather().sink(print))

for x in range(10):
    src.emit(x)
```

```
1
2
3
4
5
6
7
8
9
10
```

I'm not surprised to see things fail generally though.  This code isn't actively maintained and as we've seen there has been drift upstream.

You could also try distributed master

**Comment by seanlaw** [comment]
Same here. I can run it locally but connecting to a distributed cluster somehow makes it unhappy :(

**Comment by seanlaw** [comment]
When connecting to the client, do I need to provide any of the `processes` or `asynchronous` function arguments for an existing dask distributed cluster?

**Comment by mrocklin** [comment]
Common reason for that is a version mismatch between machines.  Might want
to run the get_versions(check=True) method.

On Oct 3, 2018 8:03 PM, "Sean M. Law" <notifications@github.com> wrote:

When connecting to the client, do I need to provide any of the processes or
asynchronous function arguments for an existing dask distributed cluster?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/mrocklin/streamz/issues/209#issuecomment-426842602>,
or mute
the thread

**Comment by seanlaw** [comment]
Hmm, checking versions on the distributed cluster causes:

```
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    client.get_versions(check=True)
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 3078, in get_versions
    packages=packages)
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/utils.py", line 277, in sync
    six.reraise(*error[0])
  File "/app/home/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/utils.py", line 262, in f
    result[0] = yield future
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/core.py", line 574, in send_recv_from_rpc
    result = yield send_recv(comm=comm, op=key, **kwargs)
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/app/home/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/core.py", line 466, in send_recv
    six.reraise(*clean_exception(**response))
  File "/app/home/miniconda3/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/core.py", line 318, in handle_comm
    close_desired = msg.pop('close', False)
TypeError: versions() got an unexpected keyword argument 'packages'
```

**Comment by mrocklin** [comment]
Definitely a version issue.  I recommend verifying that the distributed
library is uniform across your machines.

**Comment by seanlaw** [comment]
Aha, progress! Here's what I found:

1. A few of the nodes had a slightly older version of dask (and probably distributed)
2. All of the nodes except for the scheduler node were still using tornado=5.0.3 

So, I did the following (and hopefully will be a helpful checklist for others):

- [x] Killed the dask-scheduler on the scheduler node
- [x] Killed the dask-worker on each worker node
- [x] Updated the scheduler node to latest version of dask `conda update -y dask`
- [x] Updated all worker nodes to latest version of dask and distributed via `conda update -y dask`
- [x] Downgraded the scheduler node to tornado=4.5.3 via `conda install -y tornado=4.5.3`
- [x] Downgraded all worker nodes to tornado=4.5.3 via `conda install -y tornado=4.5.3`
- [x] Restarted the dask-scheduler on the scheduler node
- [x] Restarted the dask-worker on all worker nodes
- [x] Tested `client.get_versions(check=True)

And everything passed with version checking! Next, I tested this example and it produced the expected results:

```
import dask.distributed
import streamz
client = dask.distributed.Client('tcp://localhost:8786')

def increment(x):
    return x+1

src = streamz.Stream()
(src.scatter().map(increment).gather().sink(print))

for x in range(10):
    src.emit(x)
```

I am now attempting to push the limits a little with:

```
import dask.distributed
import streamz

client = dask.distributed.Client('tcp://localhost:8786')
#print(client.get_metadata)

client.get_versions(check=True, packages=[])

def increment(x):
    return x+1

src = streamz.Stream()
(src.scatter()
    .map(increment)
    .buffer(500)
    .gather()
    .sink(print)
)

while True:
    src.emit(1)
```

While this prints a bunch of 2's, it doesn't throw up and the scheduler only complains with:

```
distributed.scheduler - INFO - Remove client Client-ab14e2c0-c77a-11e8-a501-005056a59dc2
distributed.scheduler - INFO - Plugin failed with exception
Traceback (most recent call last):
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/scheduler.py", line 3853, in transition
    plugin.transition(key, start, finish2, *args, **kwargs)
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/diagnostics/graph_layout.py", line 89, in transition
    self.visible_updates.append((self.index[key], 'False'))
KeyError: 'increment-3f64cbed9f1a73be0aba2c402f28500a'
``` 

Although, commenting out the `.buffer(500)` line does cause the program to quit with same exception as we encountered before (regardless of whether we `import dask.distributed` or `import distributed`:

```
increment-3f64cbed9f1a73be0aba2c402f28500a
Traceback (most recent call last):
  File "/app/home/miniconda3/lib/python3.6/site-packages/distributed/client.py", line 1448, in _gather
    exception = st.exception
AttributeError: exception

During handling of the above exception, another exception occurred:
```

It is still impressive to see it working! :)

**Comment by mrocklin** [comment]
You might consider trying distributed master to avoid those errors.  I *think* that one of them (maybe both?) have been resolved recently.

To be clear, you would want to update to master consistently across all machines.
